Repository grain-lang/grain, pull requests merged in 2020-06, with the labels that each got.

#139 Add String stdlib
  compiler/src/middle_end/analyze_purity.ml
  compiler/test/stdlib/strings.test.gr
  compiler/test/test_end_to_end.ml
  runtime/src/lib/strings.js
  runtime/src/runtime.js
  stdlib/pervasives.gr
  stdlib/stdlib-external/string.ts
  stdlib/strings.gr
Labels: stdlib

#149 Garbage Collection
  .gitignore
  cli/bin/grain.js
  cli/bin/run.js
  compiler/grainc/grainc.ml
  compiler/src/codegen/compcore.ml
  compiler/src/codegen/compcore.mli
  compiler/src/codegen/compmod.ml
  compiler/src/codegen/mashtree.ml
  compiler/src/codegen/transl_anf.ml
  compiler/src/compile.ml
  compiler/src/middle_end/optimize_common_subexpressions.ml
  compiler/src/middle_end/optimize_tail_calls.ml
  compiler/src/parsing/location.ml
  compiler/src/typed/env.ml
  compiler/src/typed/typetexp.ml
  compiler/src/utils/wasm_utils.ml
  compiler/test/input/long_lists.gr
  compiler/test/input/sinister-tail-call-gc.gr
  compiler/test/runner.ml
  compiler/test/test_end_to_end.ml
  package.json
  runtime/package.json
  runtime/src/core/grain-module.js
  runtime/src/core/heap.js
  runtime/src/core/malloc.js
  runtime/src/core/memory.js
  runtime/src/core/runner.js
  runtime/src/core/tags.js
  runtime/src/errors/error-codes.js
  runtime/src/errors/errors.js
  runtime/src/runtime.js
  runtime/src/utils/utils.js
  runtime/webpack.common.js
  runtime/webpack.dev.js
  runtime/webpack.prod.js
  yarn.lock
Labels: gc

#165 Remove unused variables
  compiler/src/codegen/compcore.ml
  compiler/src/codegen/transl_anf.ml
Labels: cleanup

#164 Clean up heap top
  compiler/src/codegen/compcore.ml
  compiler/src/codegen/compcore.mli
Labels: cleanup
