Repository grain-lang/grain, pull requests merged in 2020-05, with the labels that each got.

#115 Fix export scoping
  compiler/src/codegen/compcore.ml
  compiler/src/codegen/transl_anf.ml
  compiler/test/test-libs/sameExport.gr
  compiler/test/test_end_to_end.ml
  stdlib/sys.gr
Labels: bug

#117 Bump @wasmer/wasi to latest
  runtime/package.json
  yarn.lock
Labels: dependencies

#119 Fix nonexported adt printing
  compiler/test/test_end_to_end.ml
  runtime/src/utils/utils.js
Labels: bug

#121 Upgrade to dune 2
  compiler/dune-project
  compiler/dune-workspace
  compiler/esy.json
  compiler/esy.lock/index.json
  compiler/esy.lock/opam/base.v0.13.2/opam
  compiler/esy.lock/opam/dune.2.5.0/opam
  compiler/esy.lock/opam/ocaml-migrate-parsetree.1.7.3/opam
  compiler/esy.lock/opam/ppx_expect.v0.13.1/opam
  compiler/grain.opam
  compiler/grain_codegen.opam
  compiler/grain_middle_end.opam
  compiler/grain_parsing.opam
  compiler/grain_typed.opam
  compiler/grain_utils.opam
  compiler/grainc.opam
  compiler/test/dune
Labels: cleanup, dependencies

#128 Update fdPwrite description
  stdlib/sys.gr
Labels: stdlib

#134 Fix doc typo in sys.gr
  stdlib/sys.gr
Labels: stdlib

#135 Add type to whence parameter in sys.gr
  stdlib/sys.gr
Labels: stdlib

#129 Break out fs from sys
  compiler/test/runner.ml
  compiler/test/stdlib/sys.file.test.gr
  compiler/test/stdlib/sys.process.test.gr
  compiler/test/stdlib/sys.test.gr
  compiler/test/test_end_to_end.ml
  stdlib/stdlib-external/fs.ts
  stdlib/stdlib-external/sys.ts
  stdlib/sys/file.gr
  stdlib/sys/process.gr
  stdlib/sys/random.gr
  stdlib/sys/time.gr
Labels: cleanup, stdlib

#136 Fix tail-call analysis for branches
  compiler/src/middle_end/analyze_tail_calls.ml
  compiler/test/input/oneBranchTail.gr
  compiler/test/test_end_to_end.ml
Labels: bug
