Repository grain-lang/grain, pull requests merged in 2020-07, with the labels that each got.

#198 Remove wasm spec dependency
  compiler/dune-project
  compiler/esy.lock/index.json
  compiler/esy.lock/opam/dune-configurator.2.6.1/opam
  compiler/esy.lock/opam/grain_wasm_spec.0.1/opam
  compiler/grain.opam
  compiler/grain_codegen.opam
  compiler/grain_middle_end.opam
  compiler/grain_parsing.opam
  compiler/grain_typed.opam
  compiler/grain_utils.opam
  compiler/grainc.opam
  compiler/src/codegen/compcore.re
  compiler/src/codegen/compcore.rei
  compiler/src/codegen/dune
  compiler/src/dune
  compiler/src/utils/dune
  compiler/src/utils/wasm_utils.re
  compiler/test/runner.re
  compiler/test/test-data/testmod.wasm
  compiler/test/test_wasm_utils.re
Labels: cleanup, dependencies

#232 [Stdlib] Standardize library names
  CONTRIBUTING.md
  compiler/src/compile.re
  compiler/test/input/long_lists.gr
  compiler/test/input/mixedPatternMatching.gr
  compiler/test/stdlib/array.test.gr
  compiler/test/stdlib/hash.test.gr
  compiler/test/stdlib/int64.test.gr
  compiler/test/stdlib/list.test.gr
  compiler/test/stdlib/map.test.gr
  compiler/test/stdlib/option.test.gr
  compiler/test/stdlib/string.test.gr
  compiler/test/test_end_to_end.re
  stdlib/array.gr
  stdlib/int64.gr
  stdlib/list.gr
  stdlib/map.gr
  stdlib/string.gr
  stdlib/sys/file.gr
Labels: stdlib

#230 cleanup: Remove workaround for old ppx_sexp_conv bug
  compiler/src/typed/types.re
Labels: cleanup
